var nationArr = [
                 {"code": "1", "name": "대한민국"},
                 {"code": "2", "name": "미국"},
                 {"code": "3", "name": "캐나다"},
                 {"code": "4", "name": "중국"},
                 {"code": "5", "name": "브라질"},
                 {"code": "6", "name": "필리핀"},
                 {"code": "7", "name": "페루"},
                 {"code": "8", "name": "프랑스"},
                 {"code": "9", "name": "독일"},
                 {"code": "10", "name": "스페인"}
                 ];
var cityArr = [
                 {"code": "1", "name": "서울", "nation_code": "1"},
                 {"code": "2", "name": "성남", "nation_code": "1"},
                 {"code": "3", "name": "수원", "nation_code": "1"},
                 {"code": "4", "name": "강릉", "nation_code": "1"},
                 {"code": "5", "name": "동해", "nation_code": "1"},
                 {"code": "6", "name": "동해", "nation_code": "1"},
                 {"code": "7", "name": "충주", "nation_code": "1"},
                 {"code": "8", "name": "가평", "nation_code": "1"},
                 {"code": "9", "name": "전주", "nation_code": "1"},
                 {"code": "10", "name": "광주", "nation_code": "1"},
                 {"code": "11", "name": "워싱턴", "nation_code": "2"},
                 {"code": "12", "name": "알래스카", "nation_code": "2"},
                 {"code": "13", "name": "캔자스", "nation_code": "2"},
                 {"code": "14", "name": "텍사스", "nation_code": "2"},
                 {"code": "15", "name": "미시시피", "nation_code": "2"},
                 {"code": "16", "name": "일리노이", "nation_code": "2"},
                 {"code": "17", "name": "켄터키", "nation_code": "2"},
                 {"code": "18", "name": "뉴욕", "nation_code": "2"},
                 {"code": "19", "name": "펜실베니아", "nation_code": "2"},
                 {"code": "20", "name": "콜로라도", "nation_code": "2"},
                 {"code": "21", "name": "토론토", "nation_code": "3"},
                 {"code": "22", "name": "퀘벡", "nation_code": "3"},
                 {"code": "23", "name": "핼리팩스", "nation_code": "3"},
                 {"code": "24", "name": "에드먼턴", "nation_code": "3"},
                 {"code": "25", "name": "세인트존스", "nation_code": "3"},
                 {"code": "26", "name": "샬럿타운", "nation_code": "3"},
                 {"code": "27", "name": "리자이나", "nation_code": "3"},
                 {"code": "28", "name": "빅토리아", "nation_code": "3"},
                 {"code": "29", "name": "위니펙", "nation_code": "3"},
                 {"code": "30", "name": "프레더릭턴", "nation_code": "3"},
                 {"code": "31", "name": "베이징", "nation_code": "4"},
                 {"code": "32", "name": "상하이", "nation_code": "4"},
                 {"code": "33", "name": "광저우", "nation_code": "4"},
                 {"code": "34", "name": "난징", "nation_code": "4"},
                 {"code": "35", "name": "칭다오", "nation_code": "4"},
                 {"code": "36", "name": "톈진", "nation_code": "4"},
                 {"code": "37", "name": "항저우", "nation_code": "4"},
                 {"code": "38", "name": "하얼빈", "nation_code": "4"},
                 {"code": "39", "name": "홍콩", "nation_code": "4"},
                 {"code": "40", "name": "상파울루", "nation_code": "4"},
                 {"code": "41", "name": "리우데자네이루", "nation_code": "5"},
                 {"code": "42", "name": "사우바도르", "nation_code": "5"},
                 {"code": "43", "name": "브라질리아", "nation_code": "5"},
                 {"code": "44", "name": "쿠리치바", "nation_code": "5"},
                 {"code": "45", "name": "쿠이아바", "nation_code": "5"},
                 {"code": "46", "name": "마나우스", "nation_code": "5"},
                 {"code": "47", "name": "포스탈레자", "nation_code": "5"},
                 {"code": "48", "name": "벨렝", "nation_code": "5"},
                 {"code": "49", "name": "포르투알레그리", "nation_code": "5"},
                 {"code": "50", "name": "캄푸그란지", "nation_code": "5"},
                 {"code": "51", "name": "마닐라", "nation_code": "6"},
                 {"code": "52", "name": "바기오", "nation_code": "6"},
                 {"code": "53", "name": "다바오", "nation_code": "6"},
                 {"code": "54", "name": "산티아고", "nation_code": "6"},
                 {"code": "55", "name": "세부", "nation_code": "6"},
                 {"code": "56", "name": "일로일로", "nation_code": "6"},
                 {"code": "57", "name": "케손시티", "nation_code": "6"},
                 {"code": "58", "name": "말라본", "nation_code": "6"},
                 {"code": "59", "name": "말라이", "nation_code": "6"},
                 {"code": "60", "name": "로하스", "nation_code": "6"},
                 {"code": "61", "name": "리마", "nation_code": "7"},
                 {"code": "62", "name": "우아초", "nation_code": "7"},
                 {"code": "63", "name": "우앙카요", "nation_code": "7"},
                 {"code": "64", "name": "치클라요", "nation_code": "7"},
                 {"code": "65", "name": "카야오", "nation_code": "7"},
                 {"code": "66", "name": "쿠스코", "nation_code": "7"},
                 {"code": "67", "name": "푸에르토말도나도", "nation_code": "7"},
                 {"code": "68", "name": "훌리아카", "nation_code": "7"},
                 {"code": "69", "name": "세로데파스코", "nation_code": "7"},
                 {"code": "70", "name": "모요밤바", "nation_code": "7"},
                 {"code": "71", "name": "파리", "nation_code": "8"},
                 {"code": "72", "name": "루앙", "nation_code": "8"},
                 {"code": "73", "name": "르블랑", "nation_code": "8"},
                 {"code": "74", "name": "뤼넬", "nation_code": "8"},
                 {"code": "75", "name": "베르사유", "nation_code": "8"},
                 {"code": "76", "name": "발랑시엔", "nation_code": "8"},
                 {"code": "77", "name": "빈", "nation_code": "8"},
                 {"code": "78", "name": "몽뤼송", "nation_code": "8"},
                 {"code": "79", "name": "메종라피트", "nation_code": "8"},
                 {"code": "80", "name": "마쟁가르브", "nation_code": "8"},
                 {"code": "81", "name": "베를린", "nation_code": "9"},
                 {"code": "82", "name": "함부르크", "nation_code": "9"},
                 {"code": "83", "name": "뮌헨", "nation_code": "9"},
                 {"code": "84", "name": "쾰른", "nation_code": "9"},
                 {"code": "85", "name": "프랑크푸르트암마인", "nation_code": "9"},
                 {"code": "86", "name": "슈투트가르트", "nation_code": "9"},
                 {"code": "87", "name": "뒤셀도르프", "nation_code": "9"},
                 {"code": "88", "name": "뉘른베르크", "nation_code": "9"},
                 {"code": "89", "name": "브레멘", "nation_code": "9"},
                 {"code": "90", "name": "본", "nation_code": "9"},
                 {"code": "91", "name": "코르도바", "nation_code": "10"},
                 {"code": "92", "name": "마드리드", "nation_code": "10"},
                 {"code": "93", "name": "바르셀로나", "nation_code": "10"},
                 {"code": "94", "name": "발렌시아", "nation_code": "10"},
                 {"code": "95", "name": "세비야", "nation_code": "10"},
                 {"code": "96", "name": "그라나다", "nation_code": "10"},
                 {"code": "97", "name": "마벨라", "nation_code": "10"},
                 {"code": "98", "name": "빌바오", "nation_code": "10"},
                 {"code": "99", "name": "세고비아", "nation_code": "10"},
                 {"code": "100", "name": "팔마데요르카", "nation_code": "10"}
               ];